name: Test invoke.py
on: [push, pull_request]

jobs:
  matrix:
    # Run on:
    # - pull requests
    # - pushes to forks (will run in the forked project with that fork's secrets)
    # - pushes to branches that are *not* pull requests
    if: |
      github.event_name == 'pull_request'
      || github.repository != 'invoke-ai/InvokeAI'
      || github.ref_protected
    strategy:
      fail-fast: false
      matrix:
        stable-diffusion-model:
          # - 'https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt'
          - 'https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt'
        os:
          - ubuntu-latest
          - macOS-12
        include:
          - os: ubuntu-latest
            environment-file: environment-lin-cuda.yml
            default-shell: bash -l {0}
          - os: macOS-12
            environment-file: environment-mac.yml
            default-shell: bash -l {0}
          # - stable-diffusion-model: https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt
          #   stable-diffusion-model-dl-path: models/ldm/stable-diffusion-v1/sd-v1-4.ckpt
          #   stable-diffusion-model-switch: stable-diffusion-1.4
          - stable-diffusion-model: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt
            stable-diffusion-model-dl-path: models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
            stable-diffusion-model-switch: diffusers-1.5
    name: ${{ matrix.os }} with ${{ matrix.stable-diffusion-model-switch }}
    runs-on: ${{ matrix.os }}
    env:
      CONDA_ENV_NAME: invokeai
      PYTHONUNBUFFERED: 1
      HAVE_SECRETS: ${{ secrets.HUGGINGFACE_TOKEN != '' }}
    defaults:
      run:
        shell: ${{ matrix.default-shell }}
    steps:
      - name: Checkout sources
        id: checkout-sources
        uses: actions/checkout@v3

      - name: create models.yaml from example
        run: cp configs/models.yaml.example configs/models.yaml

      - name: create environment.yml
        run: cp environments-and-requirements/${{ matrix.environment-file }} environment.yml

      - name: Use Cached Stable Diffusion Model
        id: cache-sd-model
        uses: actions/cache@v3
        env:
          cache-name: huggingface-${{ matrix.stable-diffusion-model-switch }}
        with:
          path: ~/.cache/huggingface
          key: ${{ env.cache-name }}

      - name: Check model availability
        if: steps.cache-sd-model.outputs.cache-hit != true && !env.HAVE_SECRETS
        run: echo -e '\a ⛔ GitHub model cache not found, and no HUGGINGFACE_TOKEN is available. Will not be able to load Stable Diffusion.' ; exit 1

      - name: Use cached conda packages
        id: use-cached-conda-packages
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: conda-pkgs-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(matrix.environment-file) }}

      - name: Activate Conda Env
        id: activate-conda-env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ env.CONDA_ENV_NAME }}
          environment-file: environment.yml
          miniconda-version: latest

      - name: set test prompt to main branch validation
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "TEST_PROMPTS=tests/preflight_prompts.txt" >> $GITHUB_ENV

      - name: set test prompt to development branch validation
        if: ${{ github.ref == 'refs/heads/development' }}
        run: echo "TEST_PROMPTS=tests/dev_prompts.txt" >> $GITHUB_ENV

      - name: set test prompt to Pull Request validation
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/development' }}
        run: echo "TEST_PROMPTS=tests/validate_pr_prompt.txt" >> $GITHUB_ENV

      - name: run preload_models.py
        id: run-preload-models
        run: |
          if [ "${HAVE_SECRETS}" == true ] ; then
            mkdir -p ~/.huggingface
            echo -n '${{ secrets.HUGGINGFACE_TOKEN }}' > ~/.huggingface/token
          fi
          python scripts/preload_models.py \
            --no-interactive

      - name: Run the tests
        id: run-tests
        run: |
          time python scripts/invoke.py \
            --model ${{ matrix.stable-diffusion-model-switch }} \
            --from_file ${{ env.TEST_PROMPTS }}

      - name: export conda env
        id: export-conda-env
        run: |
          mkdir -p outputs/img-samples
          conda env export --name ${{ env.CONDA_ENV_NAME }} > outputs/img-samples/environment-${{ runner.os }}-${{ runner.arch }}.yml

      - name: Archive results
        id: archive-results
        uses: actions/upload-artifact@v3
        with:
          name: results_${{ matrix.os }}_${{ matrix.stable-diffusion-model-switch }}
          path: outputs/img-samples
